Basic tramp support
kubernetes-el/kubernetes-el pull request #167
Opened 2021-06-18 00:09 UTC by egh

Add some basic tramp support.

Includes a new popup menu for files (`f`).

I abused the `user` parameter for tramp to support different containers for the same pod. This doesn't feel great, but since `user` is not a valid option for `kubectl exec` it shouldn't be a huge problem.

I'm unhappy with the container prompt logic. It is an option to the file commands, but magit-popup doesn't seem to support required parameters, and it would be very strange to open a file in a container without knowing which container in the pod was being used, it seems necessary to prompt the user for a container explicitly. But this feels strange with the magit-popup option as well.

I named the tramp method `kubernetes` to avoid a clash with the https://github.com/gruggiero/kubernetes-tramp project.

Screenshot of file popup menu:

![image](https://user-images.githubusercontent.com/22718/122486679-68790780-cf8e-11eb-9a38-287a07d93baf.png)

2021-06-19 09:06 UTC, noorul requested changes
When I try this feature with `f f` without `=c` on a pod with multiple containers, it picks one of the containers. But when I use `f D` it prompts me to choose a container.

2021-06-28 20:03 UTC, merged

2021-06-28 20:50 UTC, egh commented on kubernetes-tramp.el
> +               (tramp-login-args (("exec" "-i" "-t") ("-c" "%u") ("%h") ("--" "%l")))
Sorry! I've been caught up with other stuff. I will file a follow up PR

2021-06-29 13:06 UTC, tarsius commented
I noticed this issue because I try to (and mostly succeed) to ensure that there are no feature conflicts in the [Emacsmirror](https://emacsmirror.net).

> I named the tramp method `kubernetes` to avoid a clash with the https://github.com/gruggiero/kubernetes-tramp project.

There is still a conflict: it is undefined which library gets loaded when a user does `(require 'kubernetes-tramp)`. Please consider renaming the library.

2021-06-30 16:36 UTC, egh commented on kubernetes-tramp.el
> +               (tramp-login-args (("exec" "-i" "-t") ("-c" "%u") ("%h") ("--" "%l")))
Unfortunately, I'm struggling to see how to implement this in tramp directly. They don't allow such dynamic arguments for the tramp login args. I'm still trying to figure out how to make this work.