feat(configmaps): show (truncated) data in overview (#199)
kubernetes-el/kubernetes-el pull request #245
Opened 2021-12-23 09:37 UTC by Walheimat

Shows configmap data in a new section in the overview.

Both keys and values are truncated. If the value spans multiple lines, only the first line is shown (and maybe truncated). To show this truncation, a forward slash (dimmed) is shown.

Adds a new case to the configmap test response; the expected case is updated accordingly.

*Note* that for me the tests don't work, so I had to run the updated test using `cask exec ert-runner ./test/kubernetes-configmaps-test.el` (which succeeds):

```sh
➜  kubernetes-el git:(feature/cm-data-in-overview) make test
cask clean-elc
cask exec ert-runner
Debugger entered--Lisp error: (error "Test ‘kubernetes-contexts-test--empty-state’ redef...")
  error("Test `%s' redefined" kubernetes-contexts-test--empty-state)
  ert-set-test(kubernetes-contexts-test--empty-state #s(ert-test :name kubernetes-contexts-test--empty-state :documentation nil :body (closure (t) nil (let ((temp-buffer (generate-new-buffer " *temp*" t))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (save-excursion ...) (let* ... ...) (search-forward-regexp "Context:[[:space:]]+") (let* ... ...)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))) :most-recent-result nil :expected-result-type :passed :tags nil))
  load-with-code-conversion("/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." nil t)
  load("/home/walheimat/emacs/kubernetes-el/test/kubernete..." nil :nomessage)
  ert-runner--load("/home/walheimat/emacs/kubernetes-el/test/kubernete...")
  mapc(ert-runner--load ("/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..."))
  -each(("/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete..." "/home/walheimat/emacs/kubernetes-el/test/kubernete...") ert-runner--load)
  (let ((test-files (ert-runner--test-files tests)) (test-helper (f-expand "test-helper.el" ert-runner-test-path))) (-each ert-runner-load-files #'ert-runner--load) (if (f-exists\? test-helper) (ert-runner--load test-helper)) (-each test-files #'ert-runner--load) (if ert-runner-verbose (ert-runner/run-tests-batch-and-exit ert-runner-selector) (let ((shut-up-sink (generate-new-buffer " *shutup*")) (inhibit-message t)) (let* ((--cl-shut-up-current-output-- #'(lambda nil ...))) (if shut-up-ignore (progn (ert-runner/run-tests-batch-and-exit ert-runner-selector)) (unwind-protect (let* (... ... ... ... ... ...) (unwind-protect ... ... ... ...)) (and (buffer-name shut-up-sink) (kill-buffer shut-up-sink))))))))
  ert-runner/run()
  apply(ert-runner/run nil)
  commander--handle-command(nil)
  commander-parse(nil)
  (if commander-parsing-done nil (commander-parse (or commander-args (cdr command-line-args-left))))
  load-with-code-conversion("/home/walheimat/emacs/kubernetes-el/.cask/29.0/elp..." "/home/walheimat/emacs/kubernetes-el/.cask/29.0/elp..." nil t)
  command-line-1(("-scriptload" "/home/walheimat/emacs/kubernetes-el/.cask/29.0/elp..."))
  command-line()
  normal-top-level()

make: *** [Makefile:64: test] Error 255
```

2021-12-23 10:00 UTC, Walheimat commented
Looks like I missed something, will update later.

2021-12-23 17:03 UTC, jinnovation requested changes
Thanks for looking into this!

Let's also add an entry to the CHANGELOG to reflect these new additions.

2021-12-23 17:03 UTC, jinnovation commented on kubernetes-utils.el
> +(defun kubernetes-utils-ellipsize-multiline (s threshold)
Could we extend the existing `kubernetes-utils-ellipsize` to handle multi-line?

2021-12-23 17:05 UTC, jinnovation commented
> so the error comes from a redefinition. 

Do you have a sense of how that specific test (`kubernetes-contexts-test--empty-state`) is getting redefined? Curious what changes in Emacs 29 to cause this.

> Should I fix this in another PR so it works for 29?

If the fix can't be bundled into this PR, then follow-up PR is fine. Since we don't provide full support for Emacs 29, as long as CI passes we're good.

2021-12-23 19:27 UTC, Walheimat commented
If this change is okay with you, I'd rebase into a single commit.

I'll look at the test redefinition in another PR.

2021-12-24 18:43 UTC, jinnovation commented
> If this change is okay with you, I'd rebase into a single commit.

No need; I've restricted PRs to squash-and-merge only, so no need to worry about excessive commits "polluting" repo history.

> I'll look at the test redefinition in another PR.

Sounds good; thanks.

2021-12-24 18:44 UTC, jinnovation approved these changes

2021-12-24 18:44 UTC, jinnovation commented on kubernetes-utils.el
> +  "Ellipsize a string.
```suggestion
  "Ellipsize a string S that's longer than THRESHOLD.
```

2021-12-25 15:36 UTC, merged